### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by flo6913** [jefersonestevo/angular-smd#2]
Hi,
I would like to know if i can use this module.
I looked for a licensing file but i didn't find anything.
Is it possible to be clearer about this ?

**Comment by shijithkm** [comment]
Can please specify how to install fab speed dial in to our application?

**Comment by mikemwalsh** [comment]
hey @jefersonestevo - I was hoping you might be able to do this also.  I am really interested in using the speed dial - it looks great!  Unfortunately I cannot use it without a license at work :S.

Thanks for the great contribution!
Mike

**Comment by jefersonestevo** [comment]
Hello people. I haven't had much time lately for this project, but I added now a MIT License.

@shijithkm for now I'm not providing this code as a library but feel free to use it in your application as you want.

**Comment by mikemwalsh** [comment]
@jefersonestevo Thank you !!!
